name: Deploy
run-name: Deploy PoliTemporizador to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  prepare-deploy:
    runs-on: ubuntu-latest  # Changed to GitHub-hosted runner
    timeout-minutes: 5  # Add timeout to prevent hanging
    outputs:
      build-artifact: ${{ steps.set-artifact-path.outputs.download-path }}
    steps:
      - name: Descargar repo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Descargar artefacto de compilación
        id: get-artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Verificar descarga
        run: ls -la dist/  # Add verification step

      - name: Establecer ruta del artefacto
        id: set-artifact-path
        run: |
          echo "download-path=$(pwd)/dist" >> $GITHUB_OUTPUT
          echo "Artifact path: $(pwd)/dist"  # Debug output

  deploy-production:
    runs-on: ubuntu-latest  # Changed to GitHub-hosted runner
    needs: prepare-deploy
    timeout-minutes: 10  # Add timeout to prevent hanging
    steps:
      - name: Configurar entorno
        run: echo "Starting deployment..."

      - name: Usar artefacto descargado
        run: |
          echo "📂 Usando artefacto en: ${{ needs.prepare-deploy.outputs.build-artifact }}"
          ls -la ${{ needs.prepare-deploy.outputs.build-artifact }}

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ needs.prepare-deploy.outputs.build-artifact }}
          force_orphan: true
          keep_files: false

      - name: Verificar despliegue
        run: |
          echo "✅ Aplicación desplegada en:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.repository }}"
