name: Deploy
run-name: Deploy PoliTemporizador to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  prepare-deploy:
    runs-on: [self-hosted]
    outputs:
      build-artifact: ${{ steps.get-artifact.outputs.download-path }}
    steps:
      - name: Descargar repo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Descargar artefacto de compilación
        id: get-artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Establecer ruta del artefacto
        id: set-artifact-path
        run: echo "download-path=$(realpath dist)" >> $GITHUB_OUTPUT

  deploy-production:
    runs-on: [self-hosted]
    needs: prepare-deploy
    steps:
      - name: Usar artefacto descargado
        run: |
          echo "📂 Usando artefacto en: ${{ needs.prepare-deploy.outputs.build-artifact }}"
          ls -la ${{ needs.prepare-deploy.outputs.build-artifact }}

      - name: Desplegar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ needs.prepare-deploy.outputs.build-artifact }}
          force_orphan: true
          keep_files: false

      - name: Verificar despliegue
        run: |
          echo "✅ Aplicación desplegada en:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
